# Data Files
training_data_file: employee_attrition.csv
# test_data_file: test.csv

# Variables
# The variable we are attempting to predict (Survival)
target: attrition

pipeline_name: attrition_model
pipeline_save_file: attrition__model_output_v

features:      # Features that will go inside processing pipeline
  - age
  - businesstravel
  - dailyrate
  - department
  - distancefromhome
  - education
  - educationfield
  - environmentsatisfaction
  - gender
  - hourlyrate
  - jobinvolvement
  - joblevel
  - jobrole
  - jobsatisfaction
  - maritalstatus
  - monthlyincome
  - monthlyrate
  - numcompaniesworked
  - overtime
  - percentsalaryhike
  - performancerating
  - relationshipsatisfaction
  - stockoptionlevel
  - totalworkingyears
  - trainingtimeslastyear
  - worklifebalance
  - yearsatcompany
  - yearsincurrentrole
  - yearssincelastpromotion
  - yearswithcurrmanager



unused_fields:  # Features to drop before pipeline
  - employeenumber
  - employeecount
  - over18
  - standardhours


# Features names
businesstravel_var: businesstravel
dept_var: department
edu_var: educationfield
gender_var : gender
jobrole_var: jobrole
maritalsts_var: maritalstatus
overtime_var: overtime
#attrition_var: attrition
income_var: monthlyincome
compworked_var: numcompaniesworked
stock_var: stockoptionlevel
rating_var: performancerating 
workyr_var: totalworkingyears
train_var: trainingtimeslastyear
yrcomp_var: yearsatcompany
yrcurrent_var: yearsincurrentrole
yrpromotion_var: yearssincelastpromotion
yrmgr_var: yearswithcurrmanager

# Mappings for Ordinal categorical features
businesstravel_mappings: 
  Travel_Rarely : 0
  Travel_Frequently: 1
  Non-Travel: 2

dept_mappings: 
  Research & Development : 0
  Sales : 1
  Human Resources: 2

edu_mappings: 
  Life Sciences : 0
  Medical : 1
  Marketing: 2
  Technical Degree : 3
  Other : 4
  Human Resources: 5

gender_mappings: 
  Male : 0
  Female : 1

jobrole_mappings: 
  Sales Executive : 0
  Research Scientist : 1          
  Laboratory Technician : 2   
  Manufacturing Director : 3       
  Healthcare Representative : 4    
  Manager : 5                      
  Sales Representative : 6         
  Research Director : 7             
  Human Resources : 8    

martialsts_mappings: 
  Married : 0
  Single : 1          
  Divorced : 2   

overtime_mappings: 
  No : 0
  Yes : 1  

#attrition_mappings: 
  #No : 0
  #Yes : 1

 
# set train/test split
test_size: 0.20

# to set the random seed
random_state: 42
# alogrithm parameters
n_estimators: 150
max_depth: 5
max_features: 3
